// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVTTxSGltBzc58FLRGlzYkLuZ4cYrPCPw',
    appId: '1:700713087050:web:25d14184557dbd689bb6b3',
    messagingSenderId: '700713087050',
    projectId: 'makerlab-fa936',
    authDomain: 'makerlab-fa936.firebaseapp.com',
    storageBucket: 'makerlab-fa936.appspot.com',
    measurementId: 'G-RN09HX54RY',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVTTxSGltBzc58FLRGlzYkLuZ4cYrPCPw',
    appId: '1:700713087050:web:a972c52c2947bc849bb6b3',
    messagingSenderId: '700713087050',
    projectId: 'makerlab-fa936',
    authDomain: 'makerlab-fa936.firebaseapp.com',
    storageBucket: 'makerlab-fa936.appspot.com',
    measurementId: 'G-Y3CQ3J78L1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzmxOL0BsKVdLtfSzs20tVEU9mMPdGNYM',
    appId: '1:700713087050:ios:307795532ac618f29bb6b3',
    messagingSenderId: '700713087050',
    projectId: 'makerlab-fa936',
    storageBucket: 'makerlab-fa936.appspot.com',
    iosBundleId: 'com.example.jury',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzmxOL0BsKVdLtfSzs20tVEU9mMPdGNYM',
    appId: '1:700713087050:ios:307795532ac618f29bb6b3',
    messagingSenderId: '700713087050',
    projectId: 'makerlab-fa936',
    storageBucket: 'makerlab-fa936.appspot.com',
    iosBundleId: 'com.example.jury',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq9eWmtId_v8wLRKOGfLPAshgh7JiDgBU',
    appId: '1:700713087050:android:dc27b7df36520ca39bb6b3',
    messagingSenderId: '700713087050',
    projectId: 'makerlab-fa936',
    storageBucket: 'makerlab-fa936.appspot.com',
  );

}